config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  get :to_json, to: "home#to_json"
  get :to_csv, to: "home#to_csv"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crypto_coin.rb
class CryptoCoin < ApplicationRecord
  def self.instance
    find_or_create_by(singleton_lock: 1)
  end
end

app/models/investment_calculation.rb
class InvestmentCalculation
  attr_reader :eth_price, :btc_price, :eth_monthly_rate, :btc_monthly_rate,
    :initial_investment
  attr_accessor :yearly_projection

  def initialize(coin_data, initial_investment)
    @eth_price = coin_data['eth_price']&.to_f || 0.0
    @btc_price = coin_data['btc_price']&.to_f || 0.0
    @btc_monthly_rate = 1.05
    @eth_monthly_rate = 1.03
    @initial_investment = (initial_investment || 0.0)
  end

  def monthly_projection
    @yearly_projection.each_with_index do |month, index|
      month[:eth_usd_earnings] = month[:eth_earnings] * @eth_price rescue 0.0
      month[:btc_usd_earnings] = month[:btc_earnings] * @btc_price rescue 0.0
      yield month, index+1
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  around_action :sync_coin_price
  before_action :calculate_investment

  def to_csv
    attributes = %w{mes eth btc}

    csv_data = CSV.generate(headers: true) do |csv|
      csv << attributes

      @investment.monthly_projection do |month, index|
        csv << [index, month[:eth_usd_earnings], month[:btc_usd_earnings]]
      end
    end

    send_data csv_data, filename: "monthly_projection_calculator.csv"
  end

  def to_json
    investment_values = []

    @investment.monthly_projection do |month, index|
      investment_values[index] = { month: index, eth: month[:eth_usd_earnings], btc: month[:btc_usd_earnings] }
    end

    render json: investment_values.compact
  end

  private

  def calculate_investment
    coin_data = CryptoCoin.instance
    @initial_investment = params.dig(:calculation, :initial_investment) || 0.0
    @investment = InvestmentCalculationService.call(coin_data, @initial_investment)
  end

  def sync_coin_price
    yield
    SyncCoinPriceService.call(CryptoCoin.instance)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_monthly_projection.html.erb
<figure id="figure">
  <table role="grid">
    <thead>
      <tr>
        <th scope="col">Mes</th>
        <th scope="col">ETH</th>
        <th scope="col">BTC</th>
      </tr>
    </thead>
    <tbody>
    <% investment.monthly_projection do |month, index| %>
      <tr>
        <th scope="row"><%= index %> Mes</th>
        <td><%= number_to_currency(month[:eth_usd_earnings]) %></td>
        <td><%= number_to_currency(month[:btc_usd_earnings]) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</figure>

app/views/home/index.html.erb
<main class="container">
  <article class="grid">
    <div>
      <h1>Tabla de inversión</h1>
      <table role="grid">
        <thead>
          <tr>
            <th scope="col">Moneda</th>
            <th scope="col">Precio</th>
            <th scope="col">Interés mensual</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row">Bitcoin (BTC)</th>
            <td><kbd data-id='btc_price'><%= number_to_currency(@investment.btc_price, unit: 'USD') %></kbd></td>
            <td><kbd data-id='btc_tax'> 5% </kbd></td>
          </tr>
          <tr>
            <th scope="row">Ethereum (ETH)</th>
            <td><kbd data-id='eth_price'> <%= number_to_currency(@investment.eth_price, unit: 'USD') %></kbd></td>
            <td><kbd data-id='eth_tax'> 3% </kbd></td>
          </tr>
        </tbody>
      </table>
      <%= form_for(:calculation, method: :get) do |f| %>
        <%= f.number_field :initial_investment, value: @initial_investment || 0, placeholder: 'Cantidad en USD a invertir' %>
        <%= f.submit 'Calcular', data: { disable_with: 'Calculando...' } %>
      <% end %>
    </div>
  </article>
</main>

  <main class="container">
    <article class="grid">
      <div>
        <h1>Proyección mensual</h1>
        <section id="tables">
          <%= render partial: 'monthly_projection', locals: { investment: @investment } %>
        </section>
      </div>
    </article>

    <div class="grid">
      <%= link_to 'CSV', to_csv_path(calculation: { initial_investment: @initial_investment }), method: :get, class: "button primary" %>
      <%= link_to 'JSON', to_json_path(calculation: { initial_investment: @initial_investment }), method: :get, class: "button secondary" %>
    </div>

  </main
</main>

app/views/home/index.js.erb
document.getElementById('tables').innerHTML = "<%= j render partial: 'monthly_projection', locals: {investment: @investment} %>";

app/views/layouts/application.html.erb
 <!doctype html>
<html lang="es">

  <head>
    <title>Calculadora de Inversión</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <!-- Pico.css -->
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="container-fluid">
      <ul>
        <li><a href="./" class="contrast"><strong>Calculadora</strong></a></li>
      </ul>
    </nav>

    <%= yield %>

  </body>

</html>